
server:
  port: 8094
  servlet:
    context-path: /inventoryService/
    
spring:
  main:
    banner-mode: "off"
  profiles:
    active:  default # default : to run application.yml file    &&  prod : to run application-prod.yml file
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
#   type: org.apache.tomcat.jdbc.pool.DataSource
#    platform: mysql
    url: postgres://hfnxszdkilngqt:e7e1d243b94fd2de10ff871c5be151c6f282e12621fce39fe37b7a40afd572bf@ec2-54-211-77-238.compute-1.amazonaws.com:5432/d2nmtqd1b5qrse
    username: hfnxszdkilngqt
    password: e7e1d243b94fd2de10ff871c5be151c6f282e12621fce39fe37b7a40afd572bf
    initialization-mode: always
#    data: classpath:sql-file/commonConfigData.sql
    tomcat:
      initial-size: 10
      max-wait: 300000
      max-active: 200
      max-idle: 30
      min-idle: 5
      timeBetweenEvictionRunsMillis: 120000
      minEvictableIdleTimeMillis: 600000
      removeAbandoned: true
      removeAbandonedTimeout: 60


